version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  
  backend:
    image: golwin/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  
  frontend:
    image: golwin/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  
  gateway:
    image: golwin/kittygram_gateway
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 9000:80

